import { User, Event, ConnectionProfile, Match, Ticket } from './types';

export const demoUser: User = {
  id: 'demo-user',
  email: 'demo@amps.app',
  createdAt: new Date().toISOString(),
  profile: {
    name: 'Alex Demo',
    age: 28,
    bio: 'Music lover, adventure seeker, and tech enthusiast. Always looking for the next great event!',
    occupation: 'Software Developer',
    company: 'TechCorp Namibia',
    location: 'Windhoek, Namibia',
    gender: 'Non-binary',
    interests: ['Music', 'Tech', 'Travel', 'Photography', 'Art'],
    profilePhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    phone: '+264 81 123 4567',
  },
  subscription: {
    tier: 'pro',
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  settings: {
    theme: 'dark',
    currency: 'NAD',
    notifications: {
      matches: true,
      messages: true,
      events: true,
      profileViews: true,
    },
    privacy: {
      searchable: true,
      showDistance: true,
      showOnline: true,
      messageFrom: 'everyone',
    },
  },
  blockedUsers: [],
  bookmarkedEvents: ['event-1', 'event-3'],
  createdEvents: [],
  likesRemaining: 10,
  lastLikeReset: new Date().toISOString(),
};

export const demoEvents: Event[] = [
  {
    id: 'event-1',
    name: 'Windhoek Jazz Night',
    description: 'An evening of smooth jazz under the stars at the beautiful Gardens Amphitheatre. Featuring local and international artists.',
    category: 'Music',
    location: 'Gardens Amphitheatre',
    address: '123 Independence Ave, Windhoek',
    coordinates: { lat: -22.5609, lng: 17.0658 },
    date: '2026-01-15',
    time: '19:00',
    price: 150,
    currency: 'NAD',
    maxAttendees: 500,
    attendees: 342,
    organizerId: 'org-1',
    qrCode: 'jazz-night-2026',
    geofenceRadius: 200,
    customTheme: '#8B5CF6',
    coverImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    tags: ['Jazz', 'Live Music', 'Outdoor'],
    isFeatured: true,
  },
  {
    id: 'event-2',
    name: 'Tech Meetup Namibia',
    description: 'Connect with fellow tech enthusiasts, share ideas, and learn about the latest innovations in the Namibian tech scene.',
    category: 'Tech',
    location: 'Innovation Hub',
    address: '45 Tech Street, Windhoek',
    coordinates: { lat: -22.5700, lng: 17.0800 },
    date: '2026-01-20',
    time: '18:00',
    price: 0,
    currency: 'NAD',
    maxAttendees: 100,
    attendees: 67,
    organizerId: 'org-2',
    qrCode: 'tech-meetup-jan',
    geofenceRadius: 100,
    customTheme: '#3B82F6',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    tags: ['Tech', 'Networking', 'Free'],
    isFeatured: true,
  },
  {
    id: 'event-3',
    name: 'Sunset Beach Party',
    description: 'Dance the night away on the beautiful beaches of Swakopmund. DJ sets, fire dancers, and ocean vibes.',
    category: 'Party',
    location: 'Swakopmund Beach',
    address: 'Beach Road, Swakopmund',
    coordinates: { lat: -22.6792, lng: 14.5266 },
    date: '2026-01-25',
    time: '16:00',
    price: 200,
    currency: 'NAD',
    maxAttendees: 1000,
    attendees: 756,
    organizerId: 'org-3',
    qrCode: 'beach-party-2026',
    geofenceRadius: 300,
    customTheme: '#EC4899',
    coverImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    tags: ['Party', 'Beach', 'DJ'],
    isFeatured: true,
  },
  {
    id: 'event-4',
    name: 'Art Gallery Opening',
    description: 'Exclusive opening night of the new contemporary African art exhibition featuring works from emerging Namibian artists.',
    category: 'Art',
    location: 'National Art Gallery',
    address: '78 Robert Mugabe Ave, Windhoek',
    coordinates: { lat: -22.5580, lng: 17.0840 },
    date: '2026-02-01',
    time: '17:00',
    price: 75,
    currency: 'NAD',
    maxAttendees: 150,
    attendees: 89,
    organizerId: 'org-4',
    qrCode: 'art-opening-feb',
    geofenceRadius: 100,
    customTheme: '#F59E0B',
    coverImage: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800',
    tags: ['Art', 'Gallery', 'Exhibition'],
    isFeatured: false,
  },
  {
    id: 'event-5',
    name: 'Namibian Food Festival',
    description: 'Taste the best of Namibian cuisine! Local chefs showcase traditional and modern dishes from across the country.',
    category: 'Food',
    location: 'Zoo Park',
    address: 'Zoo Park, Central Windhoek',
    coordinates: { lat: -22.5690, lng: 17.0830 },
    date: '2026-02-10',
    time: '11:00',
    price: 50,
    currency: 'NAD',
    maxAttendees: 2000,
    attendees: 1234,
    organizerId: 'org-5',
    qrCode: 'food-fest-2026',
    geofenceRadius: 250,
    customTheme: '#10B981',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    tags: ['Food', 'Festival', 'Local'],
    isFeatured: true,
  },
];

export const demoConnectionProfiles: ConnectionProfile[] = [
  {
    id: 'conn-1',
    userId: 'user-1',
    eventId: 'event-1',
    name: 'Sarah Mbeki',
    age: 26,
    bio: 'Jazz enthusiast and aspiring photographer. Love meeting creative souls.',
    interests: ['Jazz', 'Photography', 'Art', 'Travel'],
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    location: 'Windhoek',
    occupation: 'Photographer',
    isPublic: true,
  },
  {
    id: 'conn-2',
    userId: 'user-2',
    eventId: 'event-1',
    name: 'Michael Chen',
    age: 31,
    bio: 'Music producer by night, developer by day. Looking for good vibes.',
    interests: ['Music', 'Tech', 'Gaming', 'Coffee'],
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    location: 'Windhoek',
    occupation: 'Music Producer',
    isPublic: true,
  },
  {
    id: 'conn-3',
    userId: 'user-3',
    eventId: 'event-1',
    name: 'Amara Nkosi',
    age: 24,
    bio: 'Event planner with a passion for connecting people. Life is better together!',
    interests: ['Events', 'Fashion', 'Dance', 'Fitness'],
    photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400',
    location: 'Swakopmund',
    occupation: 'Event Planner',
    isPublic: true,
  },
  {
    id: 'conn-4',
    userId: 'user-4',
    eventId: 'event-2',
    name: 'David Shikongo',
    age: 29,
    bio: 'Startup founder, tech enthusiast. Building the future of African fintech.',
    interests: ['Tech', 'Startups', 'Finance', 'Running'],
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    location: 'Windhoek',
    occupation: 'CEO',
    isPublic: true,
  },
  {
    id: 'conn-5',
    userId: 'user-5',
    eventId: 'event-3',
    name: 'Lena Fischer',
    age: 27,
    bio: 'Beach lover and sunset chaser. Looking for adventure partners!',
    interests: ['Beach', 'Surfing', 'Yoga', 'Travel'],
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
    location: 'Swakopmund',
    occupation: 'Travel Blogger',
    isPublic: true,
  },
];

export const demoMatches: Match[] = [
  {
    id: 'match-1',
    matchProfile: demoConnectionProfiles[0],
    eventId: 'event-1',
    eventName: 'Windhoek Jazz Night',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastMessage: 'Hey! Loved the jazz set last night 🎷',
    lastMessageTime: '2h ago',
    unread: true,
    online: true,
  },
  {
    id: 'match-2',
    matchProfile: demoConnectionProfiles[3],
    eventId: 'event-2',
    eventName: 'Tech Meetup Namibia',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    lastMessage: 'Great meeting you at the meetup!',
    lastMessageTime: '1d ago',
    unread: false,
    online: false,
  },
];

export const demoTickets: Ticket[] = [
  {
    id: 'ticket-1',
    eventId: 'event-1',
    eventName: 'Windhoek Jazz Night',
    eventDate: '2026-01-15',
    eventTime: '19:00',
    eventLocation: 'Gardens Amphitheatre',
    purchaseDate: new Date().toISOString(),
    price: 150,
    currency: 'NAD',
    quantity: 2,
    qrCode: 'JAZZ-2026-001',
    status: 'active',
  },
];
